FROM python:3.9-slim

WORKDIR /app

COPY src/ .
COPY setup.py .

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc \
    && python setup.py install \
    && apt-get remove -y gcc && apt-get -y autoremove