version: '3.7'

services:

   hello:
      build:
         context: ./
         dockerfile: Dockerfile.base
      hostname: hello
      container_name: hello
      #command: python app.py run -h 0.0.0.0
      #command: uwsgi --wsgi-file app.py --http :9090
      #command: uwsgi --socket 0.0.0.0:9090 --protocol=http -w wsgi:app
      command: uwsgi --ini uwsgi.ini
      environment: 
         FLASK_ENV: testing
      networks:
         custom-network:
            aliases:
               - hello-app
      ports:
         #- '5000:5000'
         - '5001:9090'
      volumes:
         - ./docker-volume/hello-volume/logs:/app/logs

networks:
   custom-network: