# Pull official base image
FROM arm32v7/python:3.9-alpine

# Set work directory
WORKDIR /app

# Install dependencies
RUN pip install --upgrade pip
COPY requirements.txt /app
RUN pip install -r requirements.txt

# Copy project
COPY app.py $APP_HOME

# Run python3
CMD ["python", "app.py"]