FROM python:3.9-alpine

RUN adduser -D simonuser

WORKDIR /app

COPY requirements.txt /app
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

COPY configs /app/configs
COPY src /app/src
COPY app.py wsgi.py setup.cfg boot.sh /app/
#COPY . /app

RUN chmod +x boot.sh
RUN chown -R simonuser:simonuser ./
USER simonuser

ENV PYTHONPATH "src"
ENV SERVER_HOST "0.0.0.0"

#CMD ["python3", "./app.py"]
ENTRYPOINT ["./boot.sh"]

