version: '3.7'

services:

   hello:
      build:
         context: ./
         dockerfile: Dockerfile.base
      hostname: hello
      container_name: hello
      #command: python app.py run -h 0.0.0.0
      #command: gunicorn --workers 2 --threads 2 --bind 0.0.0.0:5000 wsgi:app
      command: gunicorn --workers 2 --threads 2 --bind 0.0.0.0:5000 wsgi:app --access-logfile -
      environment: 
         FLASK_ENV: testing
      networks:
         custom-network:
            aliases:
               - hello-app
      ports:
         #- '5000:5000'
         - '5001:5000'
      volumes:
         - ./docker-volume/hello-volume/logs:/app/logs

networks:
   custom-network: