version: '3.7'

services:

   hello:
      build:
         context: ./
         dockerfile: Dockerfile.gunicorn_entrypoint
      hostname: hello
      container_name: hello
      environment: 
         FLASK_ENV: testing
      networks:
         custom-network:
            aliases:
               - hello-app
      ports:
         - '5000:5000'

   nginx:
      #image: nginx:alpine
      build:
         context: ./nginx
         dockerfile: Dockerfile.1
      container_name: nginx-hello
      restart: always
      depends_on:
         - hello
      networks:
         - custom-network
      ports:
         - 80:80
      #volumes:
         #- ./docker-volume/nginx/logs:/var/log/nginx/
         #- ./:/flask
         #- ./docker-volume/nginx-volume/nginx.conf:/etc/nginx/conf.d/nginx.conf

networks:
   custom-network: